[book]
authors = ["dr460nf1r3", "Garuda Linux Team"]
description = "Contains the documentation for the Garuda Nix subsystem"
language = "en"
src = "src"
title = "Garuda Nix Subsystem ❄️ documentation"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "mocha"
preferred-dark-theme = "mocha"
git-repository-url = "https://gitlab.com/garuda-linux/garuda-nix-subsystem"
site-url = "https://nix.garudalinux.org"
